name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: ZhouYuTao2017/next-react@master

    - name: Build and Deploy
      uses: ZhouYuTao2017/next-react@develop
      env:
        ACCESS_TOKEN: ${{ secrets.access_token }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
