name: next-react build
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: next-react build
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.access_token }}
        BRANCH: gh-pages
        FOLDER: "out"
        BUILD_SCRIPT: yarn && yarn run build
